#version 450

#extension GL_EXT_control_flow_attributes : require

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform Parameters {
    uint e;
    uint mb;
    uint nb;
};

layout(binding = 0) readonly buffer FBuf { float scr[]; };
layout(binding = 1) readonly buffer IdsBuf { int ids[]; };
layout(binding = 2) writeonly buffer DstBuf { float dst[]; };

void main() {
    const uint j = gl_GlobalInvocationID.x;
    if (j >= nb) {
        return;
    }
    const uint t = gl_WorkGroupID.y;
    const uint r = uint(ids[t]);
    if (r / mb != e) {
        return;
    }
    dst[t*nb + j] = scr[(r - e*mb)*nb + j];
}
