#version 450

#extension GL_EXT_control_flow_attributes : require

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform Parameters {
    uint d;
    uint span;
    uint vstride;
    uint gstride;
};

layout(binding = 0) buffer FBuf { float scr[]; };

void main() {
    const uint p = gl_GlobalInvocationID.x;
    if (p >= d/2u) {
        return;
    }
    const uint base = (p / span)*(span << 1) + (p % span);
    const uint i0 = gl_WorkGroupID.y*gstride + base*vstride;
    const uint i1 = i0 + span*vstride;
    const float a0 = scr[i0];
    const float a1 = scr[i1];
    scr[i0] = a0 + a1;
    scr[i1] = a0 - a1;
}
